spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ******
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
server:
  port: 8076
